### ISSUE TITLE
use `wrangler deploy` instead of publish

### ISSUE THREAD

**Issue by boomzero** [langningchen/FileShare#1]
`wrangler publish` is deprecated

**Comment by langningchen** [comment]
好的

**Comment by langningchen** [comment]
主要是因为这是 Copilot 给我写的，所以我没多注意……

**Comment by langningchen** [comment]
https://github.com/langningchen/FileShare/commit/161c333304ebfd1b1c035989419e95100d7e4375

**Comment by boomzero** [comment]
反手fork

**Comment by langningchen** [comment]
@boomzero 偷偷告诉你一个演示站： https://share.chenlangning.me/ （别攻击，尽管有 Cloudflare 防护但是很脆弱）

**Comment by langningchen** [comment]
还有就是别给我乱删文件

**Comment by boomzero** [comment]
https://github.com/XMOJ-Script-dev/FileShare

**Comment by langningchen** [comment]
> https://github.com/XMOJ-Script-dev/FileShare

😃

**Comment by langningchen** [comment]
这个网站主要是为了自己在学校和家里传文件方便，不用带 U盘

**Comment by langningchen** [comment]
我要去睡觉了
