### ISSUE TITLE
使用 `migrations` 自动初始化数据库

### ISSUE THREAD

**Issue by boomzero** [langningchen/FileShare#3]
显示: `D1_TYPE_ERROR: Type 'undefined' not supported for value 'undefined'`

是不是要run migrations?

**Comment by langningchen** [comment]
你有没有执行第九条？

**Comment by langningchen** [comment]
用那一条初始化数据库

**Comment by boomzero** [comment]
推荐创造`FileShare/migrations`

**Comment by boomzero** [comment]
> 你有没有执行第九条？

是的, thx

**Comment by boomzero** [comment]
> 推荐创造`FileShare/migrations`

那样 `wrangler d1 migrations apply xmoj-files`
就行了

**Comment by langningchen** [comment]
> 推荐创造`FileShare/migrations`

具体如何？我什么都不会

**Comment by boomzero** [comment]
> > 推荐创造`FileShare/migrations`
> 
> 具体如何？我什么都不会

把initial.sql放进去.?

**Comment by langningchen** [comment]
要么我到时候查一下这个东西怎么写吧

**Comment by langningchen** [comment]
Self note: https://developers.cloudflare.com/d1/platform/migrations

**Comment by langningchen** [comment]
4e0b05d92619e6e7d981c676f757ddf1876c8e91
