### ISSUE TITLE
[Feature request] 用户权限

### ISSUE THREAD

**Issue by boomzero** [langningchen/FileShare#4]
不然谁都能删数据

**Comment by boomzero** [comment]
或者password protection

**Comment by langningchen** [comment]
个人用的，只要不要域名扫描以及子域名扫描，你也不公开，就没问题

**Comment by boomzero** [comment]
> 个人用的，只要不要域名扫描以及子域名扫描，你也不公开，就没问题

emm

**Comment by langningchen** [comment]
不过这个我之前也想加，只不过没空写

**Comment by boomzero** [comment]
你在github上发东西会被爬

**Comment by boomzero** [comment]
比如我deploy的chatgpt就被爬了

**Comment by langningchen** [comment]
> 比如我deploy的chatgpt就被爬了

啊？好吧

**Comment by PythonSmall-Q** [comment]
有进展吗orz @langningchen

**Comment by langningchen** [comment]
@PythonSmall-Q Sorry, 最近一直在忙文化课

**Comment by langningchen** [comment]
@boomzero @PythonSmall-Q 如果能帮帮我就好了

**Comment by boomzero** [comment]
@langningchen ...

**Comment by boomzero** [comment]
you should use an auth framework

**Comment by boomzero** [comment]
but then, it is 3/30, so

**Comment by langningchen** [comment]
Emm...

**Comment by PythonSmall-Q** [comment]
蹲等解决（doge

**Comment by langningchen** [comment]
@PythonSmall-Q 中考完以后吧

**Comment by langningchen** [comment]
@boomzero @PythonSmall-Q 现在不考虑这个需求，这个只是简易的文件共享，如果用户想要安全地共享文件，可以自己使用压缩包或者其他方式添加密码

**Comment by boomzero** [comment]
> @boomzero @PythonSmall-Q 现在不考虑这个需求，这个只是简易的文件共享，如果用户想要安全地共享文件，可以自己使用压缩包或者其他方式添加密码

只是防止任何人都能点删除

**Comment by langningchen** [comment]
我最近在重写这个的原理

**Comment by langningchen** [comment]
你可以添加一个新的 Issues ，内容是只允许上传的 IP 删除文件

**Comment by langningchen** [comment]
@boomzero
